### ISSUE TITLE
Make PBR work without floating point textures

### ISSUE THREAD

**Issue by chubei-oppen** [oppenfuture/three.js#47]
Need to revert these:

- https://github.com/mrdoob/three.js/pull/22998
- https://github.com/mrdoob/three.js/pull/23060

**Comment by elalish** [comment]
@chubei-oppen I just found this issue when I was searching for any devices that fail to render PBR. Out of curiosity, why did you revert this? Did you find devices that didn't support floating point textures? I'm trying to find a repro and see how common this might be.

**Comment by chubei-oppen** [comment]
It's WeChat MiniProgram and taobao MiniProgram. They implemented WebGL on top pf OpenGL ES and didn't bother with implementing the floating texture extensions.

Devices are fine. It's the platforms.

**Comment by elalish** [comment]
Thanks, I appreciate the info!
